### ISSUE TITLE
yline

### ISSUE THREAD

**Issue by siddharthdeore** [manav20/Control-Systems#1]
https://github.com/manav20/Control-Systems/blob/6dbfacd0f1eee2d4838b2aed5f27fd9ee1cea864/Ackermann_Simulator.m#L94

yline is not available in all Matlab versions would you change it to?

`line([a1 a2],[goal goal],'Color','red','LineStyle','-.');`

**Comment by manav20** [comment]
af

**Comment by manav20** [comment]
Done.
Thanks for pointing it out.
